mpi:
  - mpich  # [unix]
  - openmpi  # [unix]
# macOS aligned_alloc support
#   https://github.com/icl-utk-edu/heffte/pull/49
#   https://stackoverflow.com/questions/44841574/aligned-alloc-not-found-for-clang/76984907#76984907
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
